const NAVIGATION_NAME = {
  LoginScreen: 'LoginScreen',
  LoginCompanyScreen: 'LoginCompanyScreen',
  MainAccount: 'MainAccount',
  ChangeStore: 'ChangeStore',
  ChangePassword: 'ChangePassword',
  HomeScreen: 'HomeScreen',
  SearchProductScreen: 'SearchProductScreen',
  ListPriceChange: 'ListPriceChange',
  ListPricePolicy: 'ListPricePolicy',
  DetailPricePolicy: 'DetailPricePolicy',
  CancelOrderStatistic: 'CancelOrderStatistic',
  CashierLoginHistory: 'CashierLoginHistory',
  ConfirmOrder: 'ConfirmOrder',
  SelectProduct: 'SelectProduct',

  ListPO: 'ListPO',
  DetailPO: 'DetailPO',
  EditPO: 'EditPO',
  ListInventoryPeriod: 'ListInventoryPeriod',
  DetailInventoryPeriod: 'DetailInventoryPeriod',
  ListLocation: 'ListLocation',
  ContactScreen: 'ContactScreen',
  ShareScreen: 'ShareScreen',
  ImportItem: 'ImportItem',
  ListApplicableStore: 'ListApplicableStore',

  //update
  ChooseCustomer: 'ChooseCustomer',
  PromotionScreen: 'PromotionScreen',
  LookUpProduct: 'LookUpProduct',
  ListSaleOrderScreen: 'ListSaleOrderScreen',
  OrderDetailScreen: 'OrderDetailScreen',
  AgentDetail: 'AgentDetail',
  AgentList: 'AgentList',
  AddCustomer: 'AddCustomer',
  MapScreen: 'MapScreen',
};

export default NAVIGATION_NAME;
