export default {
  API: {
    GetDomain: 'https://api.olbius.com/token',
    baseURL: 'https://gstest.olbius.com',
    // baseURL: 'http://10.10.4.19:8080',
    baseImgURL: 'https://testchth.olbius.com',
    Login: '/rest/s1/gsources/login',
    Logout: '/rest/logout',
    //xxxxx

    GetProductStores: '/rest/s1/gsources/getProductStores',
    GetCustomers: '/rest/s1/salesnet/mGetCustomers',
    GetPromoList: '/rest/s1/pos/getPromoList',
    QuickSearch: '/rest/s1/gsources/quickSearch',
    GetProductDetail: '/rest/s1/sales/getProductDetail',
    GetSalesOrders: '/rest/s1/salesnet/mGetSalesOrders',
    GetSalesOrderDetails: '/rest/s1/salesnet/mGetSalesOrderDetails',
    GetCustomerRegistration: '/rest/s1/salesnet/mGetCustomerRegistration',
    CreateCustomerAgent: '/rest/s1/salesnet/createCustomerAgent',
    CreateOrder: '/rest/s1/salesnet/createOrder',
    SubmitOrder: '/rest/s1/salesnet/submitOrder',
    GetAllRoute: '/rest/s1/salesnet/getAllRoute',
    SalesmanCheckIn: '/rest/s1/salesnet/salesmanCheckIn',
    SalesmanCheckOut: '/rest/s1/salesnet/salesmanCheckOut',
    GetListPriceChange: '/rest/s1/salesnet/mGetListPriceChange',
    SearchProduct: '/rest/s1/salesnet/searchProduct',
    GetListProductExpRecent: '/rest/s1/salesnet/mGetListProductExpRecent',
    UpdateQtyProductExpInvent: '/rest/s1/salesnet/mUpdateQtyProductExpInvent',
    GetInventoryCusInfo: '/rest/s1/salesnet/getInventoryCusInfo',
    UpdateInventoryCus: '/rest/s1/salesnet/updateInventoryCus',
    UpdatePasswordMobile: '/rest/s1/salesnet/mUpdatePasswordMobile',
    GetLastOrderBeingChanged: '/rest/s1/salesnet/getLastOrderBeingChanged',
    GetPromoDetail: '/rest/s1/salesnet/getPromoDetail',
    EditOrder: '/rest/s1/salesnet/editOrder',
    CancelOrder: '/rest/s1/salesnet/cancelOrder',

    //xxxx
    GetListProductStoreMobileMcs: '/getListProductStoreMobileMcs',
    GetAllProductStores: '/mGetAllProductStores',
    GetListPOMobilemcs: '/getListPOMobilemcs',
    GetListSupplierMobilemcs: '/getListSupplierMobilemcs',
    FindProductInfoMobilemcs: '/findProductInfoMobilemcs',
    FindProducts: '/mFindProducts',
    GetProductInfoMobilemcs: '/getProductInfoMobilemcs',
    GetListPriceChangeMobilemcs: '/getListPriceChangeMobilemcs',
    GetListQuotationsMobilemcs: '/getListQuotationsMobilemcs',
    GetQuotationInfoMobilemcs: '/getQuotationInfoMobilemcs',
    GetListSalesTrackMobilemcs: '/getListSalesTrackMobilemcs',
    GetListLoginPosHistoryMobilemcs: '/getListLoginPosHistoryMobilemcs',
    FindSupplierInfoMobilemcs: '/findSupplierInfoMobilemcs',
    GetListProductsMobilemcs: '/getListProductsMobilemcs',
    FindProductMobilemcs: '/findProductMobilemcs',
    GetProductBySupplierMobilemcs: '/getProductBySupplierMobilemcs',
    CalculatePOMobilemcs: '/calculatePOMobilemcs',
    CreateOrderPurchaseMobilemcs: '/createOrderPurchaseMobilemcs',
    GetDetailPOMobilemcs: '/getDetailPOMobilemcs',
    GetOrderItemEditableMobilemcs: '/getOrderItemEditableMobilemcs',
    UpdatePOMobilemcs: '/updatePOMobilemcs',
    GetStockingEventsMobilemcs: '/getStockingEventsMobilemcs',
    GetDetailStockingEventsMobilemcs: '/getDetailStockingEventsMobilemcs',
    GetStockingEventItemsMobilemcs: '/getStockingEventItemsMobilemcs',
    GetLocationsMobilemcs: '/getLocationsMobilemcs',
    ApprovePOMobilemcs: '/approvePOMobilemcs',
    CancelPOMobilemcs: '/cancelPOMobilemcs',
    UpdatePassWordMobilemcs: '/updatePassWordMobilemcs',
    GetOrderItemReceivableMobilemcs: '/getOrderItemReceivableMobilemcs',
    ReceiveInventoryFromPOMobilemcs: '/receiveInventoryFromPOMobilemcs',
  },

  RESPONSE_CODES: {
    SUCCESS: {
      SUCCESS: 200,
    },
    ERROR: {
      INTERNAL_SERVER: 500,
      NOT_FOUND: 404,
    },
  },

  ORDER_STATUS: {
    APPROVED: 'ORDER_APPROVED',
    CANCELLED: 'ORDER_CANCELLED',
    COMPLETED: 'ORDER_COMPLETED',
    CREATED: 'ORDER_CREATED',
    HOLD: 'ORDER_HOLD',
    IN_TRANSIT: 'ORDER_IN_TRANSIT',
    PROCESSING: 'ORDER_PROCESSING',
    REJECTED: 'ORDER_REJECTED',
    SADAPPROVED: 'ORDER_SADAPPROVED',
    DELIVERED: 'ORDER_DELIVERED',
  },

  GOOGLE_MAP_API: 'AIzaSyCHu4vQUKFsMnqpjk_HHjIIAU_yejvT5cs',
};
